---
title: "Bayesian Golf Analysis - BGA"
output: html_document
date: "2025-07-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)

dat_src <- "./Data/"
out_src <- "./Output/"

```

##  Bayesian golf

Each club has a distribution of distance (and width).

Shots per hole will depend on a stochastic model of distances achieved from each subsequent stroke.


```{r, echo=FALSE}

# Clubs with log-normal distributions

clubs <- c("Driver", "Hybrid5", "Iron6", "Iron8", "Iron9", "PW", "SW", "Putter")

bag <- tibble(club = factor(clubs,
                            levels = clubs,
                            labels = clubs),
              mean = c(180, 150, 120, 110, 100, 90, 80, 50),
              sd = c(30, 20, 15, 10, 10, 10, 10, 5),
              loc = log(mean^2 / sqrt(sd^2 + mean^2)),
              shp = sqrt(log(1 + (sd^2 / mean^2)))) %>%
  rowid_to_column("id")


```

## Distance distributions

https://msalganik.wordpress.com/2017/01/21/making-sense-of-the-rlnorm-function-in-r/


```{r, echo=FALSE}

# Set the parameters
set.seed(123)  # Setting seed for reproducibility
n <- 100       # Number of observations

# Generate log-normal data

shot_pattern = function(club, loc, shp){
  
  log_normal_data <- tibble(club = club,
                            dist = rlnorm(72, 
                                          meanlog = loc, 
                                          sdlog = shp))
  
  return(log_normal_data)
  
}

shot_dist <- bag %>%
  group_by(id) %>%
  group_map(~shot_pattern(.$club, .$loc, .$shp)) %>%
  bind_rows()

```

```{r, echo=FALSE}

fig1 <- ggplot() +
  geom_boxplot(data = shot_dist, aes(x = club, y = dist, fill = club),
               outlier.shape = NA) +
  geom_jitter(data = shot_dist, aes(x = club, y = dist),
              colour = "white") +
  scale_colour_brewer(palette = "Set1") +
  theme_bw() +
  labs(title = "Shot distribution by club", 
       subtitle = "Log-normal distributions") +
  ylab("Yards") +
  xlab("Club") + 
  theme(legend.position = "none",
        panel.background = element_rect(fill = 'lightgreen', 
                                        color = 'lightgreen'),
        panel.grid.major = element_line(color = 'lightgreen', linetype = 'dotted'),
        panel.grid.minor = element_line(color = 'lightgreen', linewidth = 2))

fig1

```

### Density plots

```{r, echo=FALSE}

# Change density plot line colors by groups
fig2 <- ggplot(shot_dist, aes(x = dist, color = club),
               linesize = 3) +
  geom_density() +
  geom_vline(data = bag, 
             aes(xintercept = mean, color = club),
             linetype="dashed") +
  scale_colour_brewer(palette = "Set1") +
  theme_bw() +
  labs(title = "Shot distribution by club", 
       subtitle = "Log-normal distributions") +
  ylab("Yardage") +
  xlab("Density") + 
  theme(legend.position = "right",
        panel.background = element_rect(fill = 'lightgreen', 
                                        color = 'lightgreen'),
        panel.grid.major = element_line(color = 'lightgreen', linetype = 'dotted'),
        panel.grid.minor = element_line(color = 'lightgreen', linewidth = 2))

fig2

```

